tasks:
  - name: Install Angular CLI
    init: npm install -g @angular/cli
    command: echo "Angular CLI installed."

  - name: Setup and Run Angular App
    init: |
      cd frontend
      npm install
    command: npm run dev

# Ports to expose on workspace startup
ports:
    - port: 4200
      onOpen: open-preview
      name: Frontend website
      description: Frontend Preview