image:
  file: .gitpod.Dockerfile
ports:
  - port: 5000
    onOpen: ignore
  - port: 4200
    onOpen: open-preview

tasks:
  - name: Start mysql and mongodb
    init: |
      docker-compose pull
    command: |
      docker-compose up -d
      gp sync-done finished
    openMode: split-left

  - name: Start Flask application
    init: |
      cd backend
      pip install -r requirements.txt
    # added 3 lines export lines
    command: |
      docker_host_ip=$(ip -4 addr show docker0 | grep -oP '(?<=inet\s)\d+(\.\d+){3}')
      echo "Docker Host IP: $docker_host_ip"
      export MYSQL_HOST=$docker_host_ip
      gp sync-await finished && \
      python app.py
    openMode: split-right
    dependsOn:  
      - "Start mysql and mongodb"

  - name: Start Angular application
    init: |
      cd frontend
      npm install && npm run build 
    command: |
      npm run start
