ports:
  - port: 5000
    onOpen: ignore
  - port: 4200
    onOpen: open-preview

tasks:
  - name: Start mysql and mongodb
    init: |
      docker-compose pull
    command: |
      docker-compose up -d
      gp sync-done finished
    openMode: split-left

  -name: Start Flask application
    init: |
      cd backend
      pip install -r reuirements.text
    command: |
      gp sync-await finishes && \
      flask run 
    openMode: split-right
    
  -name: Start Angular application
    init: |
      npm install && npm run build
    command: |
      npm run start