image:
  file: .gitpod.Dockerfile
ports:
  - port: 5000
    visibility: public
    onOpen: ignore
  - port: 4200
    visibility: public
    onOpen: open-preview

tasks:
  - name: Start mysql and mongodb
    init: |
      docker-compose pull
    command: |
      docker-compose up -d
      gp sync-done finished
      docker_host_ip=$(ip -4 addr show docker0 | grep -oP '(?<=inet\s)\d+(\.\d+){3}')
      echo "Docker Host IP: $docker_host_ip"
    openMode: split-left

  - name: Start Flask application
    init: |
      cd backend
      pip install -r requirements.txt
    # added 3 lines export lines
    command: |
      export FLASK_APP=app.py            
      export FLASK_ENV=development
      export FRONTEND_URL=$(gp url 4200)  
      export BACKEND_URL=$(gp url 5000) 
      docker_host_ip=$(ip -4 addr show docker0 | grep -oP '(?<=inet\s)\d+(\.\d+){3}')
      echo "Docker Host IP: $docker_host_ip" 
      export DOCKER_IP=$(ip -4 addr show docker0 | grep -oP '(?<=inet\s)\d+(\.\d+){3}')
      gp sync-await finished && \
      python app.py
    openMode: split-right

  - name: Start Angular application
    init: |
      cd frontend
      npm install && npm run build 
    command: |
      backend_url=$(gp url 5000)  # Get the backend URL
      sed -i "s|API_URL|$backend_url|g" src/environments/environment.ts  
      sed -i "s|API_URL|$backend_url|g" src/environments/environment.development.ts  
      npm run start
