image: gitpod/workspace-full

tasks:
  - name: Setup, Install and Build Frontend
    before: cd frontend
    init: npm install
    command: ng serve
# Ports to expose on workspace startup
ports:
    - port: 4200
      onOpen: open-preview
      name: Frontend website
      description: Frontend Preview