image:
  file: .gitpod.Dockerfile

tasks:
  - name: Install Dependencies
    init: |
      cd frontend
      npm install

  - name: Launch Angular Frontend
    init: |
      cd frontend
    command: ng serve --host 0.0.0.0 --port 8080

ports:
  - port: 4200
    onOpen: open-preview
