image:
  file: .gitpod.Dockerfile

tasks:
  - name: Install Dependencies
    command: |
      cd frontend
      npm install
      cd ../backend
      pip install -r requirements.txt

  - name: Start MySQL and MongoDB
    init: |
      # Start MySQL Server
      service mysql start
      # Start MongoDB
      mongod --fork --logpath /var/log/mongodb.log

  - name: Setup MySQL and MongoDB Databases
    command: |
      cd mysql
      mysql -u root < init.sql

ports:
  - port: 8080
    onOpen: open-preview

vscode:
  extensions:
    - dbaeumer.vscode-eslint

imageRegistryUrl: registry.gitpod.io
