version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  mysql:
    image: mysql:latest
    container_name: mysqldb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: student_management_system
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

#   backend:
#     build: 
#       context: ./backend
#       dockerfile: Dockerfile
#     container_name: backend
#     ports:
#       - "5000:5000"
#     environment:
#       MONGO_URI: "mongodb://mongo:27017/student-management"
#       MYSQL_HOST: mysql
#       MYSQL_USER: root
#       MYSQL_PASSWORD: root
#     networks:
#       - mynetwork
#     depends_on:
#       - mongo
#       - mysql
  
#   frontend:
#     build: 
#       context: ./frontend
#       dockerfile: Dockerfile
#     container_name: frontend
#     ports:
#       - "80:80"
#     networks:
#       - mynetwork
#     depends_on:
#       - backend

# networks:
#   mynetwork:
#     name: mynetwork

volumes:
  mongo-data:

